### ISSUE TITLE
Cross-entropy method figure has wrong Normal

### ISSUE THREAD

**Issue by mossr** [sisl/algorithmsbook#11]
In `policy_search.tex` you create the `MvNormal` with mean `[0, 1]` and covariance `I`, but then redefine the variable `p` with:

```julia
 p = MvNormal([mean(xdomain), mean(ydomain)], Matrix{Float64}(2I, 2, 2))
```

So the caption in the cross-entropy method figure (10.5) needs to be updated with `𝒩([0, 3], 2I)`

**Comment by tawheeler** [comment]
Thanks! Should be fixed now.
