### ISSUE TITLE
Clarity of *legend* on figure about Gaussian Mixture

### ISSUE THREAD

**Issue by chauvinSimon** [sisl/algorithmsbook#13]
reading `[2021-01-05 15:52:36-08:00, revision 2f3d6e6]` page 48.
First of all, congratulations for you great job!!

Here a small detail about the legend of this figure
![temp](https://user-images.githubusercontent.com/34301767/103819069-ffe64000-5069-11eb-9fd7-7ab2703cd882.png)

I am used to seeing density plots where areas under plots are 1.
If the area under the blue one should be 1, then the areas under each individual red density plots must be way smaller than 1 (which is unusual to see!).
True, you explain it well "we plot the density of two **components scaled** by their weights". But in the legend, the red plots are only said to be **"components"**.

To avoid confusions, I would suggest to **define the red legend as _"scaled components"_**.

**Comment by mykelk** [comment]
Thanks! Good catch, that could lead to confusion.

**Comment by chauvinSimon** [comment]
One could even plot the **"non-scaled components"**, together with the **"scaled components"** and the **"mixture density"** to help understand how the later is constructed.
But maybe it becomes then too much.

(I let your team close the issue)

**Comment by mykelk** [comment]
Fixed and reposted. Thanks!
