### ISSUE TITLE
(FYI) Latest version of font

### ISSUE THREAD

**Issue by cormullion** [sisl/algorithmsbook#14]
FYI, there's been an update (right) to the monospaced font since the version used for the draft of ```2021-01-05 15:52:36-08:00, revision 2f3d6e6``` (left).

<img width="1189" alt="Screenshot 2021-01-06 at 22 15 20" src="https://user-images.githubusercontent.com/52289/103824903-ba774200-506c-11eb-9366-3f116db1d9a1.png">

(There had been some criticism that the ϕ characters could be confused. 😀)

**Comment by mykelk** [comment]
Thanks! I'll fix this.

**Comment by mykelk** [comment]
Fixed and reposted. Thanks!
