### ISSUE TITLE
[minor] Formatting oddity: occasionally bold operators

### ISSUE THREAD

**Issue by cormullion** [sisl/algorithmsbook#16]
I noticed a minor oddity on line 5 here: the arithmetic operators, normally grey, are black. I only noticed because the asterisk is quite bold with this font weight, and it caught my eye. :) 

<img width="1011" alt="Screenshot 2021-01-10 at 16 19 33" src="https://user-images.githubusercontent.com/52289/104128517-e68e0e00-535f-11eb-99f9-c808c0e53130.png">

(Of course, you don't need the `*` in this particular location since `2(n + λ)` is OK... :))

**Comment by mykelk** [comment]
Good catch. I think there is an issue with the lexer: https://github.com/sisl/pygments-julia

**Comment by mykelk** [comment]
Tim made a fix to the lexer. How does this look to you?
![image](https://user-images.githubusercontent.com/6294079/104268139-0f89ce00-5448-11eb-983c-7844b153e85d.png)

**Comment by cormullion** [comment]
Looks perfect!
