### ISSUE TITLE
Independence of discrete probabilties

### ISSUE THREAD

**Issue by sambitdash** [sisl/algorithmsbook#19]
The clarification in section 2.3.1 could have been written in section 2.2.1 as well. 

For example, 
&theta;<sub>6</sub> = 1 - (&theta;<sub>1</sub> +&theta;<sub>2</sub> +...+&theta;<sub>5</sub>)

What is written is: 

_However, we need only five independent parameters to uniquely specify the distribution over the outcomes of the roll because we know that the distribution must sum to 1._

**Comment by mykelk** [comment]
True. I think 2.2.1 conveys the same idea is slightly different words.
