### ISSUE TITLE
Satellite Monitoring problem statement is missing (page 34). 

### ISSUE THREAD

**Issue by sambitdash** [sisl/algorithmsbook#20]
Section 2.5: Not clear what is the satellite monitoring problem. It kind of seems, it's a very well know problem that authors have referred to. In that case a reference to the problem discussed else where should be provided. 

Alternatively, it may help explaining Bayesian Network through the satellite monitoring sample. The mention of DAG, and function Pa(x) or parent is kind of too abstract for someone to conceive. It may help to establish it with an example and then discuss the related math.

**Comment by mykelk** [comment]
I added some additional elaboration to the caption. It's just a simple example network (originally introduced in my previous book) to illustrate the concept. The revised version will likely be posted tomorrow.
