### ISSUE TITLE
Basic BN description could be more clear

### ISSUE THREAD

**Issue by wiz21b** [sisl/algorithmsbook#22]
I've  been studying Bayesian nets for a while now (I'm a very beginner here) and something that's never quite clear is : what does an edge actually mean ? Why is there an arrow ? In 2.5:

_Directed edges connect pairs of nodes, with cycles in the graph being prohibited. The arrows
indicate direct probabilistic relationships. Associated with each node Xi is a
conditional distribution P(Xi | Pa( Xi )), where Pa( Xi ) represents the parents of_

So, what is exactly that "direct probabilistic relationship" ? Causation, correlation, conditional dependence ?

Moreover, on 2.6, it is said :

_The reason that a Bayesian network can represent a joint distribution with fewer
independent parameters than would normally be required is due to the condi-
tional independence assumptions encoded in its graphical structure._

However conditional independence is not *represented* in a BN (that is, there's no graphical representation), it is *deduced* from the BN (via d-separation if I understand correctly). Worse, what is represented with edges is conditional dependence, not independence. So it's hard to understand.

So, unless I still got no clue about what's going on (which is quite possible), I think the explanation could make things easier if it distinguished between what is represented visually and what meaning it has.

**Comment by wiz21b** [comment]
note that in the AIMA book, they just say that an arrow represents a "parent" relation which is not clear either...

**Comment by mykelk** [comment]
These are such great questions. It does not imply causality. I will add a note to the book to emphasize this. The graphical structure defined by all of the edges implies certain conditional independencies as described in the book. It is a way of representing a set of conditional independence assumptions.

It is a little tricky to say what one particular edge in isolation means beyond what we have in the text. It is along the lines of what is contained in the large volume by Koller and Friedman (Probabilistic Graphical Models): "This intuition, that “a node depends directly only on its parents,” lies at the heart of the semantics of Bayesian networks."

**Comment by wiz21b** [comment]
On Mon, 11 Jan 2021 21:59:47 +0100,
Mykel Kochenderfer wrote:
> These are such great questions. It does not imply causality. I will add a note to the book to emphasize this. The graphical structure defined by all of the edges implies certain
> conditional independencies as described in the book. It is a way of representing a set of conditional independence assumptions.

Yes of course. But the thing that was a bit tough for me to get is that the BN doesn't directly represent the conditional independence assumptions. These are deduced from what it directly represents : local conditional probabilities. Again, as a student, I tend to read things the way there are written, without interpreting much (or worse sometimes, with my own interpretation!). So, if the whole explanantion of a BN revolves around local CPT (i.e. prbabilistic dependencies), then it's not obvious that the BN helps to show (conditional) independencies because it goes in the opposite direction of the initial explanation.


> It is a little tricky to say what one particular edge in isolation means beyond what we have in the text. It is along the lines of what is contained in the large volume by Koller and
> Friedman (Probabilistic Graphical Models): "This intuition, that “a node depends directly only on its parents,” lies at the heart of the semantics of Bayesian networks."

I understand it is tricky. But then, an explicit hint about that trickiness would be fine. As a reader, that would prevent me of trying to look for meaning in places which are not appropriate. In other words saying "X is this" is good, but often, it's much easier for understanding if one *adds* that "X is not that".

(as a side note, it seems to me that computer scientists, as mathematicians, love to subsume their knowledge in the least amount of communication, whereas, as a student, I prefer to have the same thing restated from various points of view).

Besides, I found the exercices very helpful for two reasons :
- they're simple, so we actually understand that we apply theory and nothing else. With other books, exercices are often layered in two parts : first you have to figure out the problement statement (often a modelling exercise), then you have to apply the theory. When I do such an exercise, I often reach the point where I wonder if the way I apply th theory is wrong because I didn't understand it or because the first layer (modelling) is wrong. Your exercises are more straightforward so I know what I get wrong quicker and with less doubts.
- they provide complete solutions (for example, AIMA doesn't and without that you never know if you're right or wrong, making the exercise useless unless you have access to a teacher).

Finally, using a real programming language to express algorithm makes a big difference. Those who don't invariably redefine concepts which help the explanation but are detrimental to the implementation (and thus, understanding, because as a student, I try to implement algorithm). As a student, this leads me to spend as much time figuring out the language semantic as figuring out the ideas the books tries to teach.

If I have some more time, I'll give another look.

Thank you for publishing your work, that's unvaluable.

Best regards,

Stéphane

**Comment by mykelk** [comment]
Thanks for the feedback! We'll also create an example in the body of the text to further elaborate on these conditional independence assumptions. That is captured in a separate issue.
