### ISSUE TITLE
opensource the book

### ISSUE THREAD

**Issue by inet56** [sisl/algorithmsbook#24]
release the Latex source code

**Comment by mykelk** [comment]
We've released the latex book template (originally developed for Algorithms for Optimization) [here](https://github.com/sisl/tufte_algorithms_book). That's what we can release right now as far as latex source code goes. In terms of the Julia code, as mentioned in the preface: "Permission is granted, free of charge, to use the code snippets associated with this book, subject to the condition that the source of the code is acknowledged. We anticipate that others may want to contribute translations of these algorithms to other programming languages. As translations become available, we will link to them from the book’s webpage." We will eventually have a separate repo containing the algorithmic implementations, but right now we are working on getting the text right based on community feedback.
