### ISSUE TITLE
Reference for transitivity, universal comparability -> real valued probability

### ISSUE THREAD

**Issue by zsunberg** [sisl/algorithmsbook#25]
In Chapter 2, you say "Universal comparability and transitivity assumptions lead to an ability to represent plausibility by a real-valued function". It might not be immediately obvious why this is true (it is not immediately obvious to me, and I am teaching it tomorrow :cold_sweat:). In DMU, you have a reference for that statement (so I can point students to it if they ask). I think it would be helpful to also have that reference in this book.

**Comment by mykelk** [comment]
Cool. I'll add a ref to E.T. Jaynes, Probability Theory: The Logic of Science. New York: Cambridge University Press, 2003.

**Comment by tawheeler** [comment]
That is a fantastic book!

**Comment by mykelk** [comment]
Done and posted. I also clarified some of the text leading up to it.
