### ISSUE TITLE
Missing Mention of NamedTupleTools in Algorithm 2.1

### ISSUE THREAD

**Issue by TobiasLorek** [sisl/algorithmsbook#26]
You should add a mention of `NamedTupleTools` in the figure text to __algorithm 2.1__ on page 26.

Further, it's not clear why the functions

- `variablenames`
- `assignments`

are present not are they used in the chapter.

Asside from that, thanks for the book :)

**Comment by TobiasLorek** [comment]
Ok, `assignments` shows up later in the section about bayesian networks, still it added confusion and bugs, so you might want to think it over

This is written from the viiew point of a swe without any julia experience

**Comment by tawheeler** [comment]
We did an overhaul of the factor representation (to internally use dicts so that (a=1, b=2) is the same key as (b=2, a=1)). I think this was resolved in that, as we dropped NamedTupleTools and reference a short segment in the appendix with some helper code.
