### ISSUE TITLE
Page 33, Simple Illustration of concepts in a Bayesian network would add clarity

### ISSUE THREAD

**Issue by TobiasLorek** [sisl/algorithmsbook#27]
I think adding an illustration of simple 3 step Bayesian network to explain the the notation of `pa(x)` would really help with clarity, I would also suggest introducing the probability expression before starting with the code.

**Comment by mykelk** [comment]
Do you think a section introducing graph concepts (in the math concepts appendix) would be helpful in understanding parent/child/descendant relationships?

**Comment by TobiasLorek** [comment]
I was thinking something along the lines of a dummy network

```
P(A) -> P(B) -> P(C)
```

and the tabulating writing out the probability 

```
P(A=a, B=b, C=c) = P(A=a|B=b, C=c)*P(B=b|C=c)*P(C=c)
```

with a small note saying something with "here Pa(A) represents B=b, C=c", e.t..c.

I had to stop and think for a while to understand what you mean with Pa(A) and an example might have helped.

That said, I'm just a swe reading this book for fun so I might not be your intended audience

**Comment by mykelk** [comment]
Ah, it's just talking about immediate parents. So, in your example, Pa(A) = {}, Pa(B) = {A}, and Pa(C) = {B}. I think what you are describing are descendants. We can make this clear in an appendix and reference it in a sidenote.

**Comment by mykelk** [comment]
Appendix A.16 has been added to review some of these graph concepts.
