### ISSUE TITLE
Any plans for a dead tree version?

### ISSUE THREAD

**Issue by mjacar** [sisl/algorithmsbook#30]
I definitely want to express my appreciation and gratitude to you guys for putting this out for free. This is great stuff! However, for me, nothing beats the UX of actually flipping through pages. I'd be happy to pay a good premium to do so. Fair enough if there aren't enough people like me to justify this, but I'd be curious to know if you guys have kicked the tires on this at all.

**Comment by mykelk** [comment]
Thanks so much! The most important thing for us right now is to make the book as awesome as possible based on community feedback. We want to integrate comments over the next couple months, and then send it off to print. It will be full color and look like _Algorithms for Optimization_. @tawheeler already has a draft of the cover art and it looks awesome!
