### ISSUE TITLE
MPC Convexity requires linear dynamics

### ISSUE THREAD

**Issue by zsunberg** [sisl/algorithmsbook#31]
In 9.9.1, you say "A common approximation to make U(a1:d) convex is to assume deterministic dynamics." Unless, I am mistaken, to be convex, the dynamics must not only be deterministic, but also linear to make the problem convex. This is because the dynamics constraint is an equality constraint and the only type of equality constraint that is convex is a linear constraint.

Also, later you say "sampling a random transition once for each state-action input pair" is a way to get a deterministic transition, but it is not clear to me how you would do this in practice if you are dealing with uncountably infinite state and action spaces - it does not seem like you could do this in a way that results in a convex problem - in fact it is not clear to me that this would result in a continuous objective function, so even nonlinear solvers could not handle it.

**Comment by zsunberg** [comment]
I think you should say something like "A common approximation to make U(a1:d) amenable to optimization is to assume deterministic dynamics. Moreover, if these deterministic dynamics are linear, and the reward function is convex, the problem is convex."

**Comment by mykelk** [comment]
Addressing your first comment now. As for sampling a random transition for each state-action input pair, you are right that you can't do that explicitly for an infinite set. However, you can seed the random generator. It makes things deterministic, but it doesn't necessarily result in a convex formulation. You can also take your samples deterministically using say the 10th percentile from a Gaussian distribution if you want to perform well even with pessimistic predictions.

**Comment by zsunberg** [comment]
Right, regarding the second part, I just think you should change the "for each state-action input pair", probably by just referencing 9.9.2 and 9.9.3

**Comment by mykelk** [comment]
Sounds good. I'll post a new version tonight.
