### ISSUE TITLE
error in example 2.8 (conditional independence via d-separation)

### ISSUE THREAD

**Issue by kilimanjaro** [sisl/algorithmsbook#33]
In Example 2.8, to determine whether D and B are conditionally independent given F, we check the two paths between them, which have inverted forks. It is stated that "Since F is a descendant of C, there is d-separation along the inverted fork", but this is the opposite of what is prescribed in Section 2.6: namely, because F is a descendant of the fork, there is not d-separation.

**Comment by mykelk** [comment]
Thanks! Fixed! A new version will be posted by Tuesday. Thank you for filing this issue.
