### ISSUE TITLE
Algorithm 2.3 Might need more explanation

### ISSUE THREAD

**Issue by semochka** [sisl/algorithmsbook#34]
Thank you very much for putting the book on the web - this is absolutely amazing.

It seems algorithm 2.3 either has a bug or might require more explanation. For example, is it possible to compute the probability from the text that nothing is wrong - probability(bn, Assignment (b=1, s=1, e=1, d=1, c=1))?

Thank you very much,
-Simon

**Comment by mykelk** [comment]
Yes, you are right. It needs just a little more explanation. I expanded the caption a bit and a new PDF will be posted tomorrow. Thanks so much!
