### ISSUE TITLE
An error in Example 2.3 Julia v.1.5.3. The Assingments in FactorTable should be Dictionary not NamedTuple

### ISSUE THREAD

**Issue by jomavera** [sisl/algorithmsbook#36]
It worked for me like this
φ = Factor([X, Y, Z], FactorTable(
    Dict(:x=>1, :y=>1, :z=>1) => 0.08, Dict(:x=>1, :y=>1, :z=>2) => 0.31,
    Dict(:x=>1, :y=>2, :z=>1) => 0.09, Dict(:x=>1, :y=>2, :z=>2) => 0.37,
    Dict(:x=>2, :y=>2, :z=>1) => 0.02, Dict(:x=>2, :y=>2, :z=>2) => 0.07,
))

**Comment by mykelk** [comment]
In the Jan 14 version (or later), there should be a note in the caption of Example 2.3 that says: "The construction of the
factor table using named tuples takes advantage of the utility functions defined in appendix G.5." The utility functions there are:
```julia
Base.Dict{Symbol,V}(a::NamedTuple) where V =
    Dict{Symbol,V}(n=>v for (n,v) in zip(keys(a), values(a)))
Base.convert(::Type{Dict{Symbol,V}}, a::NamedTuple) where V =
    Dict{Symbol,V}(a)
Base.isequal(a::Dict{Symbol,<:Any}, nt::NamedTuple) =
    length(a) == length(nt) &&
    all(a[n] == v for (n,v) in zip(keys(nt), values(nt)))
```
The details of why this works is a bit beyond the level of Julia knowledge required for the book, but it basically just allows the named tuples to be automatically converted to dictionaries---allowing for a more natural API for the user.

**Comment by semochka** [comment]
Why doesn't it work in probability function  `probability(bn, (b=1, s=1, e=1, d=2, c=1 ))`  in the example 2.3? 

`ERROR: LoadError: MethodError: no method matching probability(::BayesianNetwork, ::NamedTuple{(:b, :s, :e, :d, :c),NTuple{5,Int64}})`

You explicitly need to convert named tuples into Assignment: `probability(bn, Assignment( (b=1, s=1, e=1, d=2, c=1) ))`

Thank you very much,
-Simon

**Comment by mykelk** [comment]
Yes. We now have a sidenote mentioning this:
![image](https://user-images.githubusercontent.com/6294079/105092671-64d06b80-5a56-11eb-9354-4f0cc6d9ea88.png)
(I'm fixing the margin intrusion now.)

If there is a more elegant way to do this, we're definitely open to other ideas. A key property that we need is for `(a=1, b=2)` is treated the same as `(b=2, a=1)`. We originally had assignments just as named tuples, but the factor table needs to be insensitive to orderings. Tim changed the implementation just recently to have assignments stored as dictionaries, but we still wanted to keep the specification of factor tables simple.

**Comment by AlexandrParkhomenko** [comment]
![=](https://user-images.githubusercontent.com/48244777/105142729-fd74f300-5b0b-11eb-8755-6b48288775ee.png)
It is not very important, but there are different symbols in pdf linux.

**Comment by tawheeler** [comment]
Wow, the source code is => in both cases. @mykel Does pygments do something special there?

**Comment by tawheeler** [comment]
I'll file this as a separate issue.

**Comment by mykelk** [comment]
Whoa... I'll take a look.

**Comment by semochka** [comment]
I perfectly understand the intention here and I should say that the automatic conversion in construction of FactorTable makes the code very elegant. 

I was just asking why the automatic conversion from named tuple to dictionary does not work for `probability` function? Why is explicit conversion required `probability(bn, Assignment((b=1, s=1, d=2,c=1)))` and not `probability(bn, (b=1, s=1, d=2,c=1))`?

Thank you,
-Simon
