### ISSUE TITLE
Explanation for the shapes of ellipses in linear+quadratic MDP

### ISSUE THREAD

**Issue by chauvinSimon** [sisl/algorithmsbook#37]
From `[2021-01-05 15:52:36-08:00, revision 2f3d6e6]`

I am reading the **Example 7.4**. "An example solving a finite-horizon MDP with a linear transition function and quadratic reward."

![gaussian dist over state](https://user-images.githubusercontent.com/34301767/105150433-0dd59f80-5b05-11eb-83c5-cc96e8a61feb.png)

I could not understand the **shapes of the ellipses**.

The legend says
> "The blue contour lines show the Gaussian distributions over the state at each iteration".

The text says
> "w is drawn from a zero-mean multivariate Gaussian distribution with covariance `0.1I`."

Since the **covariance matrix** is **proportional to the identity matrix**, I would have expected a **circular shape**. It is the case for the first step. But then it seems that the covariance matrix is not diagonal and its `[0, 0]` and `[1, 1]` elements are not even equal.

Just for illustration:
![example cov matrices](https://user-images.githubusercontent.com/34301767/105151580-68bbc680-5b06-11eb-863b-231f305ee34e.png)

Maybe I have misunderstood something here, but I think you could add an **explanation of these shapes and their evolution in the legend**.

**Comment by tawheeler** [comment]
The initial belief is circular, but it gets distorted to a non-circular shape as we propagate the belief forward using the Kalman filter.

**Comment by chauvinSimon** [comment]
Brilliant explanation! Thank you.
I think it would be very helpful to have it part of the legend, especially for the first sentence you wrote.

[That's it from my side, I let you close the issue]

**Comment by tawheeler** [comment]
Added! Thank you
