### ISSUE TITLE
Simple, routine economics application

### ISSUE THREAD

**Issue by azev77** [sisl/algorithmsbook#39]
Hi guys and thanks for posting your book! 

Economists (like myself) solve MDPs all the time and even created some toolkits: [VFIToolkit](https://github.com/vfitoolkit/VFIToolkit-matlab).m, [QuantEcon](https://github.com/QuantEcon/QuantEcon.jl).jl etc. 
Unfortunately our toolkits & [learning materials](https://julia.quantecon.org/dynamic_programming/discrete_dp.html) are segmented from others who also solve these types of problems. 
It would be awesome if economists, engineers etc all cooperated on the same packages. 

Would it be possible to include a very simple, routine economics problem? 
Perhaps the one I posted on [POMDPs](https://github.com/JuliaPOMDP/POMDPs.jl/issues/326).jl?

**Comment by mykelk** [comment]
QuantEcon.jl is a lovely package! I really like making connections to other disciplines. The reality is that many of the ideas in the book have been discovered and rediscovered in a wide variety of different fields (not just computer science!) as discussed in the first chapter. In fact, many of the core ideas come from economics. The book has at its core the maximum expected utility principle, which is pretty central to economics. The axioms justifying the existence of a utility function come from the classic Theory of Games and Economic Behavior. Dynamic programming is used quite a bit in economics. The final part of the book is on multi-agent systems, where we discuss equilibria concepts such as Nash. One of the motivating problems at the start of the book is the consumption problem by Merton. Much can be gained by understanding the fundamental problems that span multiple disciplines---unfortunately, different communities have used very different nomenclature and notation. We hope that this book will help bridge multiple communities. I use this book for a course that I teach in the Department of Aeronautics and Astronautics. Most of the students in the course do not come from that department. They come from computer science, electrical engineering, mechanical engineering, psychology, economics, business, civil engineering, math, bioengineering, management science, energy resources engineer, geological sciences, etc. and it's pretty exciting! Hopefully, we'll have more contributors to POMDPs.jl and there will be more cross-discipline collaboration as you suggest!
