### ISSUE TITLE
General Wonderful Reference for MDP Planning

### ISSUE THREAD

**Issue by Shushman** [sisl/algorithmsbook#4]
In particular, I think referencing the chapters on Heuristic Search and some of Approximation Algs would be super useful (maybe in the appendix?)

Mausam, Andrey Kolobov. "Planning with markov decision processes: an ai perspective." Morgan & Claypool Publishers (2012).

https://www.morganclaypool.com/doi/abs/10.2200/S00426ED1V01Y201206AIM017

**Comment by mykelk** [comment]
Done! Thanks for the tip!
