### ISSUE TITLE
Fuji/Xerox Printer erroring after Page 28

### ISSUE THREAD

**Issue by nigels-com** [sisl/algorithmsbook#40]
I'd sent the PDF to my local OfficeWorks in Brisbane, Australia to have a hard copy.

The job failed more than once after page 28, according to the staff there.
They were not able to offer more technical details, but I imagine there might be recursion of buffer limits in PDF streams.

Note that Letter paper is not generally available in Australia, so it was being resized for A4.

**Comment by mykelk** [comment]
I'm sorry to hear about the trouble! The PDF size matches the trim for the future print version, which is 8x9 inches. It can be rescaled to A4, but you will notice that there will be a gap at the tops and bottoms of pages (room for your notes?) To address the difficulty with the printer, I passed the PDF through ghostscript using this command:
```
gs -o dm-cmyk.pdf -sDEVICE=pdfwrite -sProcessColorModel=DeviceCMYK -sColorConversionStrategy=CMYK -sColorConversionStrategyForImages=CMYK dm.pdf
```
I uploaded the file [here](https://algorithmsbook.com/files/dm-cmyk.pdf). Would you mind verifying that it works for you? If so, I will also upload that version to the webpage.

**Comment by nigels-com** [comment]
Thank you, @mykelk we'll give that a try.

**Comment by nigels-com** [comment]
Yes, success!  Thanks.

**Comment by mykelk** [comment]
Sounds good. By default starting now, I'll only post a version that has passed through ghostscript.
