### ISSUE TITLE
Disappointment that has no analogy Algorithms for decision making. 

### ISSUE THREAD

**Issue by steveyang331** [sisl/algorithmsbook#41]
Disappointment that has no analogy Algorithms for decision making.

**Comment by mykelk** [comment]
Are you able to elaborate more on what you are looking for? Are you asking about disappointment aversion, as discussed in [this paper](https://www.princeton.edu/~fgul/g91.pdf)? Or the notion of "regret" in sequential decision making? Some references on regret in both single and multiagent systems are included in the side notes. If I misunderstood the issue, feel free to reopen and provide some additional elaboration.
