### ISSUE TITLE
Figure 2.10 typo

### ISSUE THREAD

**Issue by rptrevin** [sisl/algorithmsbook#6]
Figure 2.10 specifies that $\theta_2=1$, even though $\theta_2$ is varying across different values.

**Comment by mykelk** [comment]
The different curves are for different values for theta2 specified in the legend. Does that make sense?

**Comment by rptrevin** [comment]
> The different curves are for different values for theta2 specified in the legend. Does that make sense?

Yup, but in the description of Figure 2.10 it states "Figure 2.10. The logit model with \theta_1 = 0 and \theta_2 = 1."  Since, 
\theta_2 has different values, should it be specifying that it equals 1?

**Comment by mykelk** [comment]
Ah, maybe you have an older version? This is what it looks like to me:
![image](https://user-images.githubusercontent.com/6294079/93961643-815dd080-fd0e-11ea-9273-0ccb579eb3d9.png)

**Comment by rptrevin** [comment]
> Ah, maybe you have an older version? This is what it looks like to me:
> ![image](https://user-images.githubusercontent.com/6294079/93961643-815dd080-fd0e-11ea-9273-0ccb579eb3d9.png)

Ah...yes.  That is what it was.  Thank you!
